In [92]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [93]:
import os

os.listdir(r"C:\Users\sudha\Downloads")

['11zon_compressed-PDF.zip',
 '1703569392736.jpg',
 '1703569392742.jpg',
 '1703569392746.jpg',
 '1703569392756 (1).jpg',
 '1703569392756.jpg',
 '1703569392756.pdf',
 '1703569392765 (1).jpg',
 '1703569392765.jpg',
 '1703569392774.jpg',
 '1703569392783 (1).jpg',
 '1703569392783.jpg',
 '1st&2nd sem.pdf',
 '1st&2nd sem_11zon.pdf',
 '22-12-25, 1002 Microsoft Lens.pdf',
 '22-12-25, 1004 Microsoft Lens.pdf',
 '3rd &4th Sem.pdf',
 '3rd &4th Sem_11zon.pdf',
 '3rd&4th sem.pdf',
 '3rd&4th sem_11zon.pdf',
 'A332 ..pdf',
 'A332....pdf',
 'A332.pdf',
 'anuj.mp4',
 'archive (1).zip',
 'archive (2).zip',
 'archive (3).zip',
 'archive.zip',
 'Astra (25).pdf',
 'B330 (1).pdf',
 'B330 (2).pdf',
 'B330...pdf',
 'B330.pdf',
 'beneficiary (1).pdf',
 'beneficiary.pdf',
 'calm-waters-reflect-sunlight-near-a-secluded-island-at-dusk-showcasing-serenity-and-natural-beauty-photo.jpeg',
 'ChatGPT Image Dec 17, 2025, 11_55_29 AM.png',
 'ChatGPT Image Dec 27, 2025, 09_01_17 PM.png',
 'ChatGPT Image Dec 27, 2025, 09_02_25 PM.png',
 'Desktop',
 'desktop.ini',
 'divyanshi_resume_1.pdf',
 'divyanshi_try_resume (1).pdf',
 'divyanshi_try_resume.pdf',
 'Doc1[2] (1).docx',
 'Domicile.pdf',
 'fees 25-26.pdf',
 'fees 25-26_11zon.pdf',
 'final',
 'final (2).zip',
 'final.zip',
 'hello',
 'hello.zip',
 'IISF',
 'IISF (1).zip',
 'IISF 2025  Consent Letter Destiny Coders .pdf',
 'iisf(22)',
 'iisf(22).zip',
 'iisf(3)',
 'iisf(3).zip',
 'iisf(9)',
 'iisf(9) (1)',
 'iisf(9) (1).zip',
 'iisf(9) (2).zip',
 'iisf(9) (3)',
 'iisf(9) (3).zip',
 'iisf(9).zip',
 'IISF.zip',
 'IISFff (2)',
 'IISFff (2).zip',
 'Income 24-45.pdf',
 'Income 24-45_11zon.pdf',
 'insurance.csv',
 'Jal Astra PS2.pdf',
 'Machine Learning from Disaster.ipynb',
 'machine_learning.pdf',
 'MERIT CERTIFICATE (1).pdf',
 'MERIT CERTIFICATE (2).pdf',
 'MERIT CERTIFICATE.jpg',
 'MERIT CERTIFICATE.pdf',
 'MERIT CERTIFICATE_11zon.pdf',
 'Promotion Rule 27-11-2025 new.pdf',
 'Remedial Result Winter 23 & Summer 24_sent.csv',
 'RIL-T1.pdf',
 'rustup-init.exe',
 'SE TUTORIAL (11-12).pdf',
 'SE TUTORIAL (8-10).pdf',
 'SE TUTORIAL 5-7.pdf',
 'Sudhanhu_Resume_New.pdf',
 'Sudhanshu Gochar.pdf',
 'sudhanshu.mp4',
 'S_G_Resume_2.pdf',
 'train (2).csv',
 'try_resume (1).pdf',
 'try_resume.pdf',
 'WhatsApp Image 2025-12-17 at 5.24.12 PM.jpeg',
 'WhatsApp Image 2025-12-22 at 10.55.44 PM (1).jpeg',
 'WhatsApp Image 2025-12-22 at 10.55.44 PM.jpeg',
 'WhatsApp Video 2025-12-30 at 3.51.34 PM.mp4',
 'WhatsApp Video 2025-12-30 at 3.51.35 PM.mp4',
 'WhatsApp Video 2025-12-30 at 3.51.36 PM.mp4',
 'WhatsApp Video 2025-12-30 at 3.51.37 PM.mp4',
 'WhatsApp Video 2025-12-30 at 3.51.38 PM.mp4',
 'WhatsApp Video 2025-12-30 at 3.52.43 PM.mp4',
 'wp7481374.jpg',
 'Zoom_cm_fo42anktZ9vvrZo4_mI8yJsaBGOcXuyJliuo-tZsmp8dqup0Kcl0vA@mxlwdWHExHynAOrk_ke39e81d132f8a944_.exe']

In [94]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sudha\Downloads\insurance.csv")



df.head

<bound method NDFrame.head of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [95]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [96]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [97]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [98]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [99]:
df.duplicated().sum()

1

In [100]:
df = df.drop_duplicates()

In [101]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [102]:
df["charges"].describe()

count     1337.000000
mean     13279.121487
std      12110.359656
min       1121.873900
25%       4746.344000
50%       9386.161300
75%      16657.717450
max      63770.428010
Name: charges, dtype: float64

In [103]:
df["sex"].unique()

array(['female', 'male'], dtype=object)

In [104]:
df["sex"].unique()

array(['female', 'male'], dtype=object)

In [105]:
df.loc[:, "sex"] = df["sex"].map({
    "male": 0,
    "female": 1
}).astype(int)

In [106]:
df["sex"].unique()
df["sex"].dtype

dtype('O')

In [107]:
df.loc[:, "smoker"] = df["smoker"].map({
    "no": 0,
    "yes": 1
}).astype(int)

In [108]:
df["smoker"].unique()
df["smoker"].dtype

dtype('O')

In [109]:
df = pd.get_dummies(df, columns=["region"], drop_first=True)

In [110]:
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1337 non-null   int64
 1   sex               1337 non-null   object
 2   bmi               1337 non-null   float64
 3   children          1337 non-null   int64
 4   smoker            1337 non-null   object
 5   charges           1337 non-null   float64
 6   region_northwest  1337 non-null   int32
 7   region_southeast  1337 non-null   int32
 8   region_southwest  1337 non-null   int32
dtypes: float64(2), int32(3), int64(2), object(2)
memory usage: 88.8+ KB

In [112]:
df["sex"].value_counts(dropna=False)
df["smoker"].value_counts(dropna=False)

smoker
0    1063
1     274
Name: count, dtype: int64

In [113]:
df["sex"] = df["sex"].astype(int)
df["smoker"] = df["smoker"].astype(int)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1337 non-null   int64
 1   sex               1337 non-null   int32
 2   bmi               1337 non-null   float64
 3   children          1337 non-null   int64
 4   smoker            1337 non-null   int32
 5   charges           1337 non-null   float64
 6   region_northwest  1337 non-null   int32
 7   region_southeast  1337 non-null   int32
 8   region_southwest  1337 non-null   int32
dtypes: float64(2), int32(5), int64(2)
memory usage: 78.3 KB

In [115]:
df.select_dtypes(include="object")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1337 rows x 0 columns]

In [116]:
df.info()
df.isnull().sum()
df.select_dtypes(include="object")

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1337 non-null   int64
 1   sex               1337 non-null   int32
 2   bmi               1337 non-null   float64
 3   children          1337 non-null   int64
 4   smoker            1337 non-null   int32
 5   charges           1337 non-null   float64
 6   region_northwest  1337 non-null   int32
 7   region_southeast  1337 non-null   int32
 8   region_southwest  1337 non-null   int32
dtypes: float64(2), int32(5), int64(2)
memory usage: 78.3 KB

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1337 rows x 0 columns]

In [117]:
X = df.drop("charges", axis=1)
y = df["charges"]

In [118]:
print(X.shape)
print(y.shape)

(1337, 8)
(1337,)

In [119]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [120]:
print(X_train.shape)
print(X_test.shape)

(1069, 8)
(268, 8)

In [121]:
# Separate features and target
X = df.drop("charges", axis=1)
y = df["charges"]

# Check
print(X.shape)
print(y.shape)

(1337, 8)
(1337,)

In [122]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Check sizes
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(1069, 8) (268, 8)
(1069,) (268,)

In [123]:
X_train.isnull().sum()

age                 0
sex                 0
bmi                 0
children            0
smoker              0
region_northwest    0
region_southeast    0
region_southwest    0
dtype: int64

In [124]:
from sklearn.linear_model import LinearRegression

# Create model
lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

LinearRegression()

In [125]:
y_pred = lr.predict(X_test)

In [126]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("RMSE:", rmse)

R2 Score: 0.8069287081198011
RMSE: 5956.342894363589

In [127]:
from sklearn.ensemble import RandomForestRegressor

In [128]:
rf = RandomForestRegressor(
    n_estimators=200,      # number of trees
    random_state=42
)

In [129]:
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [130]:
y_pred_rf = rf.predict(X_test)

In [131]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

r2_rf = r2_score(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Random Forest R2:", r2_rf)
print("Random Forest RMSE:", rmse_rf)

Random Forest R2: 0.8806098990278537
Random Forest RMSE: 4683.87180013619